---
name: hello
services:
  hello-1:
    image: bob2606/hello-http:0.8.27
    container_name: hello-1
    hostname: hello-1
    restart: always
    ports:
      - 81:8080
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxynet
      - traefik.http.routers.hello_1.rule=Host(`hello-1.stage.lan`)
    networks:
      proxynet:
      hellonet:

  hello-2:
    image: bob2606/hello-http:0.8.27
    container_name: hello-2
    hostname: hello-2
    restart: always
    ports:
      - 82:8080
    networks:
      proxynet:
      hellonet:
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxynet
      - traefik.http.routers.hello_2.rule=PathPrefix(`/hello-2`)
      - traefik.http.middlewares.striphello_2.stripprefix.prefixes=/hello-2
      - traefik.http.routers.hello_2.middlewares=striphello_2

  hello-3:
    image: bob2606/hello-http:0.8.27
    container_name: hello-3
    hostname: hello-3
    restart: always
    ports:
      - 83:8080
    networks:
      proxynet:
      hellonet:
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxynet
      - traefik.http.routers.hello_3.rule=(Host(`hello-3.stage.lan`) && PathPrefix(`/hello-3`))
      - traefik.http.middlewares.striphello_3.stripprefix.prefixes=/hello-3
      - traefik.http.routers.hello_3.middlewares=striphello_3

networks:
  hellonet:
  proxynet:
    name: traefik_proxynet
    external: true
