---
name: busy

services:
  busy:
    image: busybox:1.28
    container_name: busy
    hostname: busy
    environment:
      - USER=bob
      - PASSWORD=azerty
    volumes:
      - ./html:/data
      - busyvol:/config
      - mariadb:/db
    command:
      - sleep
      - "3600"
    networks:
      busy:
        ipv4_address: 172.32.0.10 
      lempnet:
    restart: always

networks:
  busy:
    name: busynet
    ipam:
      config:
      - subnet: 172.32.0.0/24
        gateway: 172.32.0.254
    driver_opts:
      com.docker.network.bridge.name: busynet0
  lempnet:
    name: lempnet
    external: true

volumes:
  busyvol:
  mariadb:
    external: true
