---
name: lempnet
services:
  web:
    image: nginx:1.26
    container_name: www
    hostname: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      lempnet:
        ipv4_address: 172.30.0.100

  php:
    image: php-mysql:8.2-fpm
    build:
      context: .
      dockerfile_inline: |
        FROM php:8.2-fpm
        RUN  docker-php-ext-install pdo_mysql
    container_name: php
    hostname: php
    restart: always
    volumes:
      - ./html:/var/www/html
    networks:
      lempnet:
        ipv4_address: 172.30.0.150
      dbnet:
        ipv4_address: 172.31.0.150

  db:
    image: mariadb:10.8
    container_name: mariadb
    hostname: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=azerty
      - MARIADB_DATABASE=stage
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    networks:
      dbnet:
        ipv4_address: 172.31.0.100

networks:
  lempnet:
    ipam:
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.254
    driver_opts:
      com.docker.network.bridge.name: lempnet0
  dbnet:
    ipam:
      config:
        - subnet: 172.31.0.0/16
          gateway: 172.31.0.254
    driver_opts:
      com.docker.network.bridge.name: dbnet0

volumes:
  mariadb:
