---
x-logging: &default-logging
  logging:
    options:
      max-file: 10
      max-size: 5m

name: lempnet
services:
  web:
    image: nginx:1.26
    container_name: www
    hostname: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx-conf:/etc/nginx/conf.d
    healthcheck:
      test: ["CMD-SHELL","curl --fail http://localhost/index.html"]
      interval: 2s
      retries: 2
      start_period: 0s
    networks:
      lempnet:
        ipv4_address: 172.30.0.100
    depends_on:
      php:
        condition: service_healthy
    <<: *default-logging

  php:
    image: php-status:8.2-fpm
    container_name: php
    hostname: php
    restart: always
    volumes:
      - ./html:/var/www/html
      - ./phptool:/tools
    healthcheck:
      test: ["CMD-SHELL","/tools/php-fpm-healthcheck"]
      interval: 2s
      retries: 2
      start_period: 5s
    networks:
      lempnet:
        ipv4_address: 172.30.0.150
      dbnet:
        ipv4_address: 172.31.0.150
    <<: *default-logging

  db:
    image: mariadb:10.8
    container_name: mariadb
    hostname: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=azerty
      - MARIADB_DATABASE=stage
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    networks:
      dbnet:
        ipv4_address: 172.31.0.100
    <<: *default-logging

networks:
  lempnet:
    ipam:
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.254
    driver_opts:
      com.docker.network.bridge.name: lempnet0
  dbnet:
    ipam:
      config:
        - subnet: 172.31.0.0/16
          gateway: 172.31.0.254
    driver_opts:
      com.docker.network.bridge.name: dbnet0

volumes:
  mariadb:
