---
name: busy

services:
  busy:
    image: busybox:${BUSY_IMAGE_TAG}
    container_name: busy
    hostname: busy
    environment:
      - USER=bob
      - PASSWORD=${PASSWORD}
    volumes:
      - ./html:/data
      - busyvol:/config
      - mariadb:/db
    command:
      - sleep
      - "3600"
    networks:
      busy:
        ipv4_address: ${BUSY_NETWORK}.${BUSY_IPV4}
      lempnet:
    restart: always

networks:
  busy:
    name: busynet
    ipam:
      config:
        - subnet: ${BUSY_NETWORK}.0/24
          gateway: ${BUSY_NETWORK}.254
    driver_opts:
      com.docker.network.bridge.name: busynet0
  lempnet:
    name: lempnet
    external: true

volumes:
  busyvol:
  mariadb:
    external: true
