---
services:
  www:
    image: nginx:1.26
    ports:
      - 80:80
    volumes:
      - html:/usr/share/nginx/html
      - nginx:/etc/nginx/conf.d
    deploy:
      replicas: 2

  php:
    image: php:8.2-fpm
    volumes:
      - html:/var/www/html
    deploy:
      replicas: 2

volumes:
  html:
    driver_opts:
      type: nfs
      o: addr=192.168.56.200,vers=4.2
      device: ":/html"
  nginx:
    driver_opts:
      type: nfs
      o: addr=192.168.56.200,vers=4.2
      device: ":/nginx-conf"
