---
services:
  proxy:
    image: traefik:v2
    container_name: proxy
    hostname: proxy
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - ./conf/traefik.yml:/etc/traefik/traefik.yml
      - /run/docker.sock:/run/docker.sock
    restart: always
    networks:
      proxynet:

  errorhandler:
    image: nginx:1.26
    container_name: errorhandler
    networks:
      proxynet:
    volumes:
      - ./errorpages:/usr/share/nginx/html
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.errhandler.rule=Host(`errorhandler`)

networks:
  proxynet:
