---
services:
  proxy:
    image: traefik:v2
    container_name: proxy
    hostname: proxy
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - ./conf/traefik.yml:/etc/traefik/traefik.yml
      - /run/docker.sock:/run/docker.sock
    restart: always
    networks:
      proxynet:

networks:
  proxynet:
